### ISSUE TITLE
Trouble running on NodeJS

### ISSUE THREAD

**Issue by singpolyma** [massiveinteractive/MassiveUnit#168]
I know the docs say to add `-lib hxnodejs` but that's already there in the default `test.hxml` and adding it to the command line does nothing.  Getting this:

```
$ haxelib run munit test -js
Massive Unit - Copyright 2019 Massive Interactive. Version 2.3.4
   haxe -main TestMain -D nodejs -lib munit -lib hamcrest -lib hxnodejs -cp test -js build/js_test.js

MUnit Results
------------------------------
Class: ExampleTest ..
==============================
PASSED
Tests: 2  Passed: 2  Failed: 0 Errors: 0 Ignored: 0 Time: 0.208

Error running 'node'
	
/home/singpolyma/src/cbor-haxe/build/js_test.js:921
	throw new js__$Boot_HaxeError("Unable to create XMLHttpRequest object.");
	^
Error: Unable to create XMLHttpRequest object.
    at Function.js_Browser.createXMLHttpRequest (/home/singpolyma/src/cbor-haxe/build/js_test.js:921:8)
    at haxe_Http.request (/home/singpolyma/src/cbor-haxe/build/js_test.js:509:33)
    at massive_munit_client_URLRequest.send (/home/singpolyma/src/cbor-haxe/build/js_test.js:2036:15)
    at Function.massive_munit_client_HTTPClient.dispatchNextRequest (/home/singpolyma/src/cbor-haxe/build/js_test.js:1956:10)
    at massive_munit_client_HTTPClient.sendResult (/home/singpolyma/src/cbor-haxe/build/js_test.js:1994:36)
    at massive_munit_client_HTTPClient.reportFinalStatistics (/home/singpolyma/src/cbor-haxe/build/js_test.js:1982:8)
    at massive_munit_TestRunner.execute (/home/singpolyma/src/cbor-haxe/build/js_test.js:1546:12)
    at massive_munit_TestRunner.asyncResponseHandler (/home/singpolyma/src/cbor-haxe/build/js_test.js:1655:8)
    at massive_munit_async_AsyncDelegate.delayActualResponseHandler (/home/singpolyma/src/cbor-haxe/build/js_test.js:1754:17)
    at f (/home/singpolyma/src/cbor-haxe/build/js_test.js:2716:242)

	
Error: Error (1) running /home/singpolyma/src/cbor-haxe/build/js_test.js
```

**Comment by singpolyma** [comment]
Hmm, upgrading `haxe` from `3.2.1` to `3.4.7` fixed this
